name: CompassTracker
version: ${project.version}
main: lol.hyper.compasstracker.CompassTracker
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/compasstracker.79938/
description: A hunter vs. speedrunner plugin.
permissions:
  compasstracker.start:
    default: op
    description: Allows the usage of /ct start
  compasstracker.setplayer:
    default: op
    description: Allows the usage of /ct setplayer
  compasstracker.stop:
    default: op
    description: Allows the usage of /ct stop
  compasstracker.removeplayer:
    default: op
    description: Allows the usage of /ct removeplayer
  compasstracker.addhunter:
    default: op
    description: Allows the usage of /ct addhunter
  compasstracker.removehunter:
    default: op
    description: Allows the usage of /ct removehunter
commands:
  ct:
    usage: /ct
libraries:
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-api:4.10.1
  - net.kyori:adventure-platform-bukkit:4.1.0