name: CompassTracker
version: ${project.version}
main: lol.hyper.compasstracker.CompassTracker
api-version: 1.13
author: hyperdefined
permission:
  compasstracker.start:
    default: op
  compasstracker.setplayer:
    default: op
  compasstracker.stop:
    default: op
  compasstracker.removeplayer:
    default: op
  compasstracker.addhunter:
    default: op
  compasstracker.removehunter:
    default: op
commands:
  ct:
    usage: /ct
